### ISSUE TITLE
How add https to docker container as default rather than http ?

### ISSUE THREAD

**Issue by MohamedBenighil** [dimzrio/docker-compose#2]
I launched docker container using Rancher 2 and when i click on its URL it takes me to http://xx.xxx.xxx.xx:32000

But i would like is : it takes me to directly to https://xx.xxx.xxx.xx:32000  (https instead of http).

please how can i do that ?

Any help would appriciated!

**Comment by mandrelbrotset** [comment]
Most likely http redirection to https was configured.
